vim.g.loaded_perl_provier = 0

require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
-- We use autopairs in cmp instead
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.indentline"
require "user.alpha"
require "user.whichkey"
require "user.autocommands"
require "vsspacevim.cinnamon"
require "vsspacevim.vgit"
require "vsspacevim.neogit"
require "vsspacevim.surround"

